feat: initial CLI commit
ReVanced/revanced-api pull request #127
Opened 2023-11-23 21:24 UTC by alexandreteles

![image](https://github.com/ReVanced/revanced-api/assets/1757773/8a3d1c16-e775-4665-beda-1cd1a63f21f4)

2023-11-23 21:54 UTC, alexandreteles commented
Imagine being stopped by code coverage. It couldn't be me.

Anyway, to use the CLI, you will need the following:

### The obvious
Install all dependencies. Use `poetry install`, `poetry update`, or install from the requirements files.

### The not so obvious
Export a GitHub token to your env: `export GITHUB_TOKEN=my_amazing_token`

Then just ./cli.py

Everything else should be exploratory. The CLI uses the docstrings to generate help, so rewriting is trivial if something isn't clear. I will write instrumentation around it so it can be used from actions, but the design decision about how that can be achieved adequately from calling repositories needs more consideration.

I think the @ReVanced/infrastructure team also lacks people with experience in writing Github actions, so @PalmDevs, I might need your help with this.

2023-11-23 23:07 UTC, oSumAtrIX requested changes
- Are internal types such as JSONResponse or "dictionary" to be documented in places such as the command spec instead of saying "A json string" or "key value pair"?
- I have not reviewed all CLI command descriptions but many were incomplete/incorrect and need to be looked into
- Instead of having a release and releases command you should only provide "releases" with additional arguments to specify the tag (including the alias tag "latest") and a list of releases
- What is the purpose of the options "get_file_path", "get_filitered_repositories" or "scaffold"?
- May be out of scope but, the routes contributors and team could be merged with an argument to only retrieve the contributors that are present in the org (aka the team)

2023-11-23 23:07 UTC, oSumAtrIX commented on cli.py
> +    CLI for the ReVanced API.
```suggestion
    CLI for ReVanced API.
```

2023-11-23 23:07 UTC, oSumAtrIX commented on cli.py
> +    def get_filtered_repositories(self) -> list[str]:
Missing comment

2023-11-23 23:07 UTC, oSumAtrIX commented on cli.py
> +    def helper(self, name=None):
Missing comment

2023-11-23 23:07 UTC, oSumAtrIX commented on api/manager.py
> +    Returns a dictionary containing a list of the main ReVanced tools.
This description is incorrect

2023-11-23 23:07 UTC, oSumAtrIX commented on api/compat.py
> +    Retrieve a list of releases for a GitHub repository.
Incorrect description

2023-11-23 23:07 UTC, oSumAtrIX commented on api/compat.py
> +    Retrieve a list of releases for a GitHub repository.
Incorrect description

2023-11-23 23:07 UTC, oSumAtrIX commented on api/github.py
> +    Retrieve a list of releases for a GitHub repository.
Incorrect description

2023-11-23 23:07 UTC, oSumAtrIX commented on api/github.py
> +@cli.helper(name="project-contributors")
Simplify to "contributors"

2023-11-23 23:07 UTC, oSumAtrIX commented on api/github.py
> +@cli.helper(name="team-members")
Simplify to "team"

2023-11-23 23:07 UTC, oSumAtrIX commented on api/compat.py
> +@cli.helper(name="tools")
May be out of scope for this PR but with the routes manager and patches this route is obsolete

2024-07-08 12:10 UTC, oSumAtrIX commented
Superseded by https://github.com/ReVanced/revanced-api/pull/169, thanks

2024-07-08 12:10 UTC, closed without merging